# Travis-CI configuration file for SuperTuxKart
#
# Configuration manual:
# http://docs.travis-ci.com/user/build-configuration/
#
language: cpp
compiler:
  - gcc

before_install:
  # Update repos
  - sudo apt-get update -qq

  # Install chroot system -- chroot debootstrap
  - date
  - pwd
  - sudo apt-get install dchroot schroot debootstrap
  - date
  - cat /etc/schroot/schroot.conf
  - sudo bash $TRAVIS_BUILD_DIR/linux-conf-command
  - cat /etc/schroot/schroot.conf
  - mkdir /home/travis/srv
  - ls -l /home/travis/srv

  # Install chroot system -- debootstrap install jail
  - ls -ld /usr/share/debootstrap/scripts/*
  - grep 'apt' /usr/share/debootstrap/scripts/gutsy
  - sudo sed -e 's/\"apt\"/\"apt sudo\"/' -i /usr/share/debootstrap/scripts/gutsy
  - grep 'apt' /usr/share/debootstrap/scripts/gutsy
  - sudo debootstrap --variant=minbase --arch amd64 trusty /home/travis/srv
  - sudo touch        /home/travis/srv/chroot-in-srv
  - sudo mkdir -p     /home/travis/srv/home/travis
  - sudo chown travis /home/travis/srv/home/travis
  - sudo chgrp travis /home/travis/srv/home/travis
  - ls -ld /home/travis/srv/*
  - sudo grep travis /etc/sudoers
  - sudo cat  /etc/sudoers
  - schroot -c trusty -- pwd
  - schroot -c trusty -- ls -l
  - schroot -c trusty -- ls -l /
  - exit 1
  - schroot -c trusty -- sudo cat /etc/shadow

  # Install chroot dependencies
  - schroot -c trusty -- sudo apt-get update -qq
  - schroot -c trusty -- sudo apt-get install build-essential cmake
  - schroot -c trusty -- sudo apt-get install libogg-dev libvorbis-dev libopenal-dev
  - schroot -c trusty -- sudo apt-get install libxxf86vm-dev libcurl4-openssl-dev
  - schroot -c trusty -- sudo apt-get install libfribidi-dev libbluetooth-dev
  - schroot -c trusty -- sudo apt-get install libgl1-mesa-dev libglu1-mesa-dev

  - ls -l
  - schroot -c trusty -- bash $TRAVIS_BUILD_DIR/linux-chroot-command
  - date
  - ls -l

  # Install dependencies
  - sudo apt-get install build-essential 
  # Display system info
  - ls -l
  - pwd
  - whoami
  - uname -a
  - echo "TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR"
  - echo "TRAVIS_BRANCH    $TRAVIS_BRANCH"
  - date
  - cat now
  - ls -la $HOME
  - pwd

script:
  #  Build commands
  - pwd
  - mkdir build
  - cd build
  #- make VERBOSE=1 -j 4
  - pwd
  - echo "this is a test deploy" > runme
  - cat runme

