# Travis-CI configuration file for SuperTuxKart
#
# Configuration manual:
# http://docs.travis-ci.com/user/build-configuration/
#
language: cpp
compiler:
  - gcc

before_install:
  # Update repos
  - sudo apt-get update -qq

  # Install chroot system
  - date
  - sudo apt-get install dchroot schroot debootstrap
  - date
  - mkdir /home/travis/srv
  - sudo debootstrap --variant=buildd --arch amd64 trusty /home/travis/srv
  - cat /etc/schroot/schroot.conf
  - sudo bash linux-conf-command
  - cat /etc/schroot/schroot.conf
  - sudo touch        /home/travis/srv/chroot-in-srv
  - sudo mkdir -p     /home/travis/srv/home/travis
  - sudo chown travis /home/travis/srv/home/travis
  - sudo chgrp travis /home/travis/srv/home/travis
  - schroot -c trusty pwd
  - schroot -c trusty ls -l
  - schroot -c trusty ls -l /
  #- schroot -c trusty bash linux-chroot-command
  - date

  # Install dependencies
  - sudo apt-get install build-essential 
  # Display system info
  - ls -l
  - pwd
  - whoami
  - uname -a
  - echo "TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR"
  - echo "TRAVIS_BRANCH    $TRAVIS_BRANCH"
  - date
  - cat now
  - ls -la $HOME
  #- mkdir ../../chroot
  - cd    ../../chroot
  - pwd

script:
  #  Build commands
  - pwd
  - mkdir build
  - cd build
  #- make VERBOSE=1 -j 4
  - pwd
  - echo "this is a test deploy" > runme
  - cat runme

