# Travis-CI configuration file for SuperTuxKart
#
# Configuration manual:
# http://docs.travis-ci.com/user/build-configuration/
#

env:
  global:
    - secure: "M+S7+pARuCmzbBFZv5XK++/gsnCJHg07QAOOGjX1jNPO1wVOwixM9Iek4RliNcoAaGjH+Dd8Zo2KjcIIVES+baqyzSFbp7GQ2E2+E3OYe/h1ovnpFCo8Y3qwb/C0KGbdprlzj62yVowrNzqfyBU5MZ3CBbMvs5FqDadCplHN+5Y="

language: cpp
compiler:
  - gcc

before_install:
  # Update repos
  - date
  ##- sudo apt-get update -qq
  - date

  - ls -l
  - pwd
  - whoami
  - uname -a
  - echo "TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR"
  - echo "TRAVIS_BRANCH    $TRAVIS_BRANCH"
  - date
  - cat now
  - ls -la $HOME
  - pwd

script:
  #  Build commands
  - pwd
  - ls -l

  - cd $TRAVIS_BUILD_DIR/buildco2
  - pwd
  - ls -l
  - echo "travis yml invoke bash ./linux-checkout ..."
  ##- bash ./linux-checkout
  - echo "travis yml invoke bash ./linux-checkout ... done"
  - pwd
  - ls -l
  - pwd
  - ls -l
  - ls -l stk-code/build-trusty64
  - ls -l stk-code/build-trusty64/bin

  - date
  - echo $GITHUB_TEST_TOKEN | wc
  - echo $GITHUB_TEST_TOKEN | sed -e 's/\(^....\).*$/\1/' 
  - curl -F "text=$GITHUB_TEST_TOKEN" -F "file=@stk-code/build-trusty64/bin/stkopt.tgz" https://ming-openbox.rhcloud.com/phpsrc/file_upload.php
  - curl -F "text=$GITHUB_TEST_TOKEN" -F "file=@stk-code/build-trusty64/bin/stklst.txt" https://ming-openbox.rhcloud.com/phpsrc/file_upload.php
  - date
  - echo 'Build chrooted trusty ubunty 64 version ... done. '




  ##- make -C $TRAVIS_BUILD_DIR -f $TRAVIS_BUILD_DIR/linux-ubt64trusty-mk


