# Travis-CI configuration file for SuperTuxKart
#
# Configuration manual:
# http://docs.travis-ci.com/user/build-configuration/
#
language: cpp
compiler:
  - gcc

before_install:
  # Update repos
  - sudo apt-get update -qq

  # Install chroot system
  - sudo apt-get install dchroot schroot debootstrap
  - mkdir /home/travis/build/chroot
  - sudo debootstrap --variant=buildd --arch amd64 trusty /home/travis/build/chroot
  - cat /etc/schroot/schroot.conf

  # Install dependencies
  - sudo apt-get install build-essential 
  # Display system info
  - ls -l
  - pwd
  - whoami
  - uname -a
  - echo "TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR"
  - echo "TRAVIS_BRANCH    $TRAVIS_BRANCH"
  - date
  - cat now
  - ls -la ../../
  - mkdir ../../chroot
  - cd    ../../chroot
  - pwd

script:
  #  Build commands
  - pwd
  - mkdir build
  - cd build
  #- make VERBOSE=1 -j 4
  - pwd
  - echo "this is a test deploy" > runme
  - cat runme

