# Travis-CI configuration file for SuperTuxKart
#
# Configuration manual:
# http://docs.travis-ci.com/user/build-configuration/
#
language: cpp
compiler:
  - gcc
#branches:
#  only:
#    - master
before_install:
  # Update repos
  - sudo apt-get update -qq
  # Install dependencies
  - sudo apt-get install build-essential 
  # Display system info
  - ls -l
  - pwd
  - uname -a
  - date
  - cat now
script:
  #  Build commands
  - mkdir build
  - cd build
  #- make VERBOSE=1 -j 4
  - echo "this is a test deploy" > runme
deploy:
  provider: releases
  api_key:
    secure: HYmpKHu1qof/HkJ6stM0T1ImKdbc32TZ9pHmAKa7y4g5ubXDZCGSQwhp8IHGXYEgwkiuXJFjVmiF7VA5
  file: build/runme
  on:
    repo: mingpj2/cxx-ci-trial


