#!/bin/bash

echo grep 'Essential' /usr/share/debootstrap/scripts/gutsy
     grep 'Essential' /usr/share/debootstrap/scripts/gutsy

echo sed ...
  sudo sed -e 's/Essential: yes)\"/Essential: yes) sudo cmake libogg-dev libvorbis-dev libopenal-dev libxxf86vm-dev libcurl4-openssl-dev libfribidi-dev libbluetooth-dev libgl1-mesa-dev libglu1-mesa-dev \"/' -i /usr/share/debootstrap/scripts/gutsy

echo grep 'Essential' /usr/share/debootstrap/scripts/gutsy
     grep 'Essential' /usr/share/debootstrap/scripts/gutsy

