#!/bin/bash

echo 'echo ''travis ALL=(ALL) NOPASSWD:ALL'' >> '/home/travis/srv/etc/sudoers

echo 'travis ALL=(ALL) NOPASSWD:ALL' >> /home/travis/srv/etc/sudoers


echo cp /etc/resolv.conf /home/travis/srv/etc/
     cp /etc/resolv.conf /home/travis/srv/etc/


echo cat /home/travis/srv/etc/apt/sources.list
     cat /home/travis/srv/etc/apt/sources.list

echo sed ...
     sed -e 's/ main/ main universe/' -i  /home/travis/srv/etc/apt/sources.list

echo cat /home/travis/srv/etc/apt/sources.list
     cat /home/travis/srv/etc/apt/sources.list

echo mount /proc /sys /dev
mount -o bind /proc  /home/travis/srv/proc
mount -o bind /sys   /home/travis/srv/sys
mount -o bind /dev   /home/travis/srv/dev
mount -o bind /home/travis  /home/travis/srv/home/travis

echo add user passwd and group
grep travis /etc/passwd 
grep travis /etc/group  

grep travis /etc/passwd >>  /home/travis/srv/etc/passwd
grep travis /etc/group  >>  /home/travis/srv/etc/group 

