#!/bin/bash

GITHUB_INNER_REPO=$(cat prjinnrepo)


DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "cd ${DIR}"
cd ${DIR}

rc=0
dstamp=$(date +"%m%d%H%I")

echo pwd
pwd

echo 'ls -l'
ls -l

cd $GITHUB_INNER_REPO
echo pwd
pwd
echo cat ../xlog-hash1
cat ../xlog-hash1

suffix=$(cat ../xlog-hash1)-$dstamp


  mkdir build-trusty64
  cd build-trusty64

  cmake .. -DCHECK_ASSETS=off -DCMAKE_INSTALL_PREFIX=../stkopt -DCMAKE_BUILD_TYPE=Debug
  ##make VERBOSE=1 -j 4
  make -j 4

  objcopy --only-keep-debug bin/supertuxkart bin/supertuxkart.dbgsymbols
  strip bin/supertuxkart
  mkdir bindbg
  cp bin/supertuxkart.dbgsymbols bindbg
  objcopy --add-gnu-debuglink=bindbg/supertuxkart.dbgsymbols bin/supertuxkart

  make install
  echo pwd
  pwd
  echo 'ls -l bin'
  ls -l bin
  echo 'ls -l ../stkopt'
  ls -l ../stkopt

  mv ../stkopt/bin/supertuxkart ../stkopt/
  mv ../stkopt/share/supertuxkart/data ../stkopt/
  rm -r ../stkopt/bin ../stkopt/share

  ln -s ../stk-assets/karts    ../stkopt/data/karts
  ln -s ../stk-assets/music    ../stkopt/data/music
  ln -s ../stk-assets/models   ../stkopt/data/models  
  ln -s ../stk-assets/sfx      ../stkopt/data/sfx  
  ln -s ../stk-assets/textures ../stkopt/data/textures
  ln -s ../stk-assets/tracks   ../stkopt/data/tracks  

  echo " " > ../stkopt/readme
  date >> ../stkopt/readme
  echo " " >> ../stkopt/readme
  echo "Get assets by svn co : " >> ../stkopt/readme
  echo "  https://svn.code.sf.net/p/supertuxkart/code/stk-assets" >> ../stkopt/readme
  echo " " >> ../stkopt/readme
  echo "Then link into data/ these assets dirs (or create stk-assets/ or a link beside data/): " >> ../stkopt/readme
  echo "  karts music sfx textures tracks" >> ../stkopt/readme
  echo " " >> ../stkopt/readme
  echo "Download links: " >> ../stkopt/readme
  echo "  curl https://ming-openbox.rhcloud.com/uploadlist/upload_file_list.txt" >> ../stkopt/readme
  echo "  curl -o t.tgz https://ming-openbox.rhcloud.com/phpsrc/file_download.php?file=stkopt.tgz-020" >> ../stkopt/readme
  echo " " >> ../stkopt/readme
  echo "Run the game: run the \"go\" command." >> ../stkopt/readme
  echo " " >> ../stkopt/readme

  echo '#!/bin/bash' > ../stkopt/go
  echo 'DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"' >> ../stkopt/go
  echo 'HOME=$DIR $DIR/supertuxkart $*' >> ../stkopt/go
  chmod a+rx ../stkopt/go

  echo 'ls -l ../stkopt'
  ls -l ../stkopt

  tar zcf bin/stkopt.tgz ../stkopt/
  tar zcf bin/stksym.tgz bin/supertuxkart.dbgsymbols
  ls -l bin > stklst.txt
  mv stklst.txt bin/
  date
  mv bin/supertuxkart bin/supertuxkart-trusty64-$suffix
  echo 'ls -l bin'
  ls -l bin
  date

echo pwd
pwd

if [ $? -ne 0 ]; then rc=1; fi

ls -l

echo "cd ${DIR}"
cd ${DIR}

echo 'ls -l'
ls -l


echo
echo "TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR"
echo "TRAVIS_BRANCH    $TRAVIS_BRANCH   "
echo

echo "rc $rc"
echo

exit $rc


