#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "cd ${DIR}"
cd ${DIR}

echo pwd
pwd

echo 'ls -l'
ls -l


tobuild="unknown"
donebuild="unknown"

if [ -f hashtobuild -a -f hashdonebuild ]; then
 tobuild=$( cat hashtobuild )
 donebuild=$( cat hashdonebuild )
fi


rc=0
dstamp=$(date +"%m%d%H%I")


if [ $tobuild == $donebuild ]; then
    echo "The hash to build " $tobuild " equals to the hash done " $donebuild " ."
    echo "Nothing do do."
else
    git clone --depth=50 --branch=master https://github.com/mingpj2/cxx-ci-inner
    cd cxx-ci-inner
    git log --pretty=oneline > ../xlog-all-lines
    cat ../xlog-all-lines | sed -e 's/^\(.......\)[^ ]*/\1/' > ../xlog-all-short
    head -n 1 ../xlog-all-short | sed -e 's/ .*//' > ../xlog-hash1
    cat ../xlog-hash1

    echo "cd ${DIR}"
    cd ${DIR}
    ls -l 
    if [ -f xlog-hash1 ]; then
        make -f linux-buildco1-ubt64trusty-mk
        if [ $? -ne 0 ]; then
            rc=1
        fi
    fi
fi

echo 'ls -l'
ls -l


echo
echo "TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR"
echo "TRAVIS_BRANCH    $TRAVIS_BRANCH   "
echo

echo "rc $rc"
echo
exit $rc


