#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "cd ${DIR}"
cd ${DIR}

rc=0
dstamp=$(date +"%m%d%H%I")

echo pwd
pwd

echo 'ls -l'
ls -l

cd cxx-ci-inner
cat ../hashtobuild

suffix=$(cat ../hashtobuild)
exename=aout-trusty-$suffix
g++ -DBLD_NUM=$dstamp -DBLD_HASH="\"$suffix\"" test.cpp -o $exename
aout-trusty-$(cat ../hashtobuild)
if [ $? -ne 0 ]; then rc=1 fi

if [ -f $exename ]; then
    chmod +x $exename
    ./exename
fi

ls -l

echo "cd ${DIR}"
cd ${DIR}

echo 'ls -l'
ls -l


echo
echo "TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR"
echo "TRAVIS_BRANCH    $TRAVIS_BRANCH   "
echo

echo "rc $rc"
echo
exit $rc


