#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "cd ${DIR}"
cd ${DIR}

rc=0
dstamp=$(date +"%m%d%H%I")

echo pwd
pwd

echo 'ls -l'
ls -l

cd cxx-ci-inner
echo pwd
pwd
echo cat ../xlog-hash1
cat ../xlog-hash1

suffix=$(cat ../xlog-hash1)
exename=aout-trusty-$suffix

g++ -DBLD_NUM=$dstamp -DBLD_HASH="\"$suffix\"" test.cpp -o $exename
if [ $? -ne 0 ]; then rc=1; fi

if [ -f $exename ]; then
    echo "Run the built binary executible ..."
    chmod +x $exename
    ./$exename
    echo
fi

ls -l

echo "cd ${DIR}"
cd ${DIR}

echo 'ls -l'
ls -l


echo
echo "TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR"
echo "TRAVIS_BRANCH    $TRAVIS_BRANCH   "
echo

echo "rc $rc"
echo

exit $rc


