#!/bin/bash

export DEBIAN_FRONTEND=noninteractive

##echo 'yes | apt-get -y install netbase'

rm /etc/protocols
rm /etc/services
apt-get -y install netbase

##build-essential cmake


# stackoverflow.com: 
# Is it possibe to answer dialog questions when installing under docker?
# 
# The answer is debconf-set-selections. Manpage: 
# http://manpages.ubuntu.com/manpages/oneiric/en/man1/debconf-set-selections.1.html
#
# To find the options that can be set use debconf-get-selections on a system 
# that already has the package installed. You'll need to install debconf-utils 
# for the second command.

